src/Entity/Configuration.php
<?php
/**
 * Class Configuration générale de l'application
 */
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ConfigurationRepository")
 * @Vich\Uploadable()
 */
class Configuration
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_open;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $app_title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $message_inscription;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $message_atelier;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $confirmation_inscription;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $confirmation_atelier;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Fichier", cascade={"persist", "remove"})
     */
    private $background_image;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Fichier", cascade={"persist", "remove"})
     */
    private $app_logo;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Fichier", cascade={"persist", "remove"})
     */
    private $autorisation_parentale;

    public function __construct()
    {
        $this->is_open = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsOpen(): ?bool
    {
        return $this->is_open;
    }

    public function setIsOpen(bool $is_open): self
    {
        $this->is_open = $is_open;

        return $this;
    }

    public function getAppTitle(): ?string
    {
        return $this->app_title;
    }

    public function setAppTitle(string $app_title): self
    {
        $this->app_title = $app_title;

        return $this;
    }

    public function getMessageInscription(): ?string
    {
        return $this->message_inscription;
    }

    public function setMessageInscription(string $message_inscription): self
    {
        $this->message_inscription = $message_inscription;

        return $this;
    }

    public function getMessageAtelier(): ?string
    {
        return $this->message_atelier;
    }

    public function setMessageAtelier(string $message_atelier): self
    {
        $this->message_atelier = $message_atelier;

        return $this;
    }

    public function getConfirmationInscription(): ?string
    {
        return $this->confirmation_inscription;
    }

    public function setConfirmationInscription(string $confirmation_inscription): self
    {
        $this->confirmation_inscription = $confirmation_inscription;

        return $this;
    }

    public function getConfirmationAtelier(): ?string
    {
        return $this->confirmation_atelier;
    }

    public function setConfirmationAtelier(string $confirmation_atelier): self
    {
        $this->confirmation_atelier = $confirmation_atelier;

        return $this;
    }

    public function getBackgroundImage(): ?Fichier
    {
        return $this->background_image;
    }

    public function setBackgroundImage(?Fichier $background_image): self
    {
        $this->background_image = $background_image;

        return $this;
    }

    public function getAppLogo(): ?Fichier
    {
        return $this->app_logo;
    }

    public function setAppLogo(?Fichier $app_logo): self
    {
        $this->app_logo = $app_logo;

        return $this;
    }

    public function getAutorisationParentale(): ?Fichier
    {
        return $this->autorisation_parentale;
    }

    public function setAutorisationParentale(?Fichier $autorisation_parentale): self
    {
        $this->autorisation_parentale = $autorisation_parentale;

        return $this;
    }
}

src/Entity/Fichier.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Entity\File as EmbeddedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
class Fichier
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    // ... other fields

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="fichier", fileNameProperty="image.name", size="image.size", mimeType="image.mimeType", originalName="image.originalName", dimensions="image.dimensions")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Embedded(class="Vich\UploaderBundle\Entity\File")
     *
     * @var EmbeddedFile
     */
    private $image;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTime
     */
    private $updatedAt;

    public function __construct()
    {
        $this->image = new EmbeddedFile();
    }

    public function getId(){
        return $this->id;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|UploadedFile $imageFile
     */
    public function setImageFile(?File $imageFile = null)
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImage(EmbeddedFile $image)
    {
        $this->image = $image;
    }

    public function getImage(): ?EmbeddedFile
    {
        return $this->image;
    }

    public function getImageName(){
        return $this->image->getName();
    }

}

templates/front/formation/confirmation.html.twig
{% extends "front_layout.html.twig" %}
{% block page_title "Formulaire d'inscription pour les inititations" %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="alert alert-success">
                    {% include 'mails/formation/email.html.twig' with { inscription: inscription } %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/front/formation/inscription.html.twig
{% extends("front_layout.html.twig") %}
{% block page_title "Formulaire d'inscription pour les inititations" %}
{% block body %}
    {# configuration \App\Entity\Configuration #}
    <div class="container">
 <div class="row">
            <div class="col">
                {{ configuration.messageInscription|raw }}
            </div>
        </div>
        <div class="row">
            {% if form.horaire.vars.choices|length != 0 %}
                <div class="col">
                    {{ form_start(form) }}
                    <section class="card">
                        <div class="card-header">
                            <h2 class="card-title">Créneau horaire</h2>
                        </div>
                        <div class="card-body">
                            {{ form_row(form.horaire) }}
                            {{ form_row(form.classeNiveau) }}
                        </div>
                    </section>
                    <div class="row">
                        <div class="col-md-6 col-xs-12 mt-4">
                            <section class="card">
                                <div class="card-header">
                                    <h2 class="card-title">Enseignants / Animateurs</h2>
                                </div>
                                <div class="card-body">
                                    {{ form_row(form.enseignantNom) }}
                                    {{ form_row(form.enseignantPrenom) }}
                                    {{ form_row(form.telEnseignant) }}
                                    {{ form_row(form.enseignantMailPro) }}
                                    {{ form_row(form.enseignantMailPerso) }}
                                </div>
                            </section>
                        </div>
                        <div class="col-md-6 col-xs-12 mt-4">
                            <section class="card">
                                <div class="card-header">
                                    <h2 class="card-title">Établissement scolaire</h2>
                                </div>
                                <div class="card-body">
                                    {{ form_row(form.nomEtablissement) }}
                                    {{ form_row(form.adresseEtablissement) }}
                                    {{ form_row(form.nomDirecteur) }}
                                    {{ form_row(form.telEtablissement) }}
                                    {{ form_row(form.emailEtablissement) }}
                                </div>
                            </section>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 mt-4">
                            <section class="card">
                                <div class="card-header">
                                    <h2 class="card-title">Autres informations</h2>
                                </div>
                                <div class="card-body">
                                    {{ form_row(form.classeNombreEleve) }}
                                    {{ form_row(form.autreInfos) }}
                                </div>
                            </section>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 mt-4">
                            <div class="alert alert-danger">
                                <h2>Droits photos</h2>
                                <p>
                                    {{ "autorisation_parentale"|trans }}
                                </p>
                                {% if configuration.autorisationParentale is defined and configuration.autorisationParentale.imageName is not null %}
                                    <p class="text-center">
                                        <a href="{{ vich_uploader_asset(configuration.autorisationParentale, "imageFile") }}"
                                           class="btn btn-danger" target="_blank">télécharger le document</a>
                                    </p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <p class="text-center">
                                <input type="submit" class="btn btn-primary" value="{{ "button.add"|trans }}"/>
                            </p>
                        </div>
                    </div>
                    {{ form_rest(form) }}
                    {{ form_end(form) }}
                </div>
            {% else %}
                <div class="col">
                    <div class="alert alert-info">
                        Il n'y a plus de places disponibles pour le moment, merci de votre participation !
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}